### ISSUE TITLE
Possibility to choose which interface connects to the network

### ISSUE THREAD

**Issue by cusspvz** [fopina/wicd-webui#1]
Firstly, congrats for this, will help me a lot! :+1: 

Secondly, is there a chance to have a `select` to set which Wireless interface connects to the network?

My python skills are smaller than electrons... hahaha

**Comment by fopina** [comment]
Hey! Sorry I've missed the notification on this issue and I only noticed now that I came back to use this..

I'm not sure we can select the interface with `wicd`, but if you want the same interface all the time (just not the default one), you can configure wicd to use that interface only (and leave the hostapd network running in the other one).

Check `wireless_interface` in the _/etc/wicd/manager-settings.conf_

**Comment by cusspvz** [comment]
Thanks for responding!

Well, I've moved along and got to use the RPi back with `OpenWRT`. I wanted to build an auto-connector Wifi RPi with 14 Interfaces from scratch, but it was easier to deploy such with OpenWRT and their `uci`.

If you're using this as well, maybe this tip could help you. :)
